FROM python:3.10.12-slim-bullseye

MAINTAINER Hang

# 设置 label
LABEL project="zjfx"

# apt 更新
RUN apt-get update -y &&  \
    apt -y upgrade && \
    apt-get install -y openssh-server openssh-client && \
    echo root:123456 | chpasswd && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean && \
    apt-get autoclean

# 安装 python 包
COPY ./requirements.txt /dockerbuild/requirements.txt
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir  -i https://pypi.tuna.tsinghua.edu.cn/simple -r /dockerbuild/requirements.txt && \
    pip cache purge

COPY ./Dockerfile-dev /dockerbuild/Dockerfile-dev

CMD /bin/bash
