FROM python:3.10.12-alpine3.18

MAINTAINER Hang

# 设置 label
LABEL project="zjfx"

# 安装 python 包
COPY ./requirements.txt /dockerbuild/requirements.txt
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir  -i https://pypi.tuna.tsinghua.edu.cn/simple -r /dockerbuild/requirements.txt && \
    pip cache purge

COPY ./Dockerfile-prod /dockerbuild/Dockerfile-prod

CMD /bin/bash
