version: '3.4'

services:

  jupyterlab-liangzhixing:
    image: "minquan-course-anaconda-env:1.0"
    container_name: liangzhixing
    environment:
      - NAME=liangzhixing
      - PSW=xx529
    ports:
      - "1800:8888"
      - "1200:22"
    volumes:
      - "/home/liangzhixing:/home/liangzhixing"
      - "/data/projects:/data/projects"
    restart: always
    
  jupyterlab-ubuntu:
    image: "minquan-course-anaconda-env:1.0"
    container_name: ubuntu
    environment:
      - NAME=ubuntu
      - PSW=ubuntu
    ports:
      - "9888:8888"
      - "9022:22"
    volumes:
      - "/home/ubuntu:/home/ubuntu"
      - "/data/projects:/data/projects"
    restart: always
